In [116]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


1) Importing the data set

In [117]:
data_yelp = pd.read_csv('yelp_labelled.txt', sep = '\t', header = None)

In [118]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [119]:
# Assign Column names 
column_name = ['Review', 'Sentiment']
data_yelp.columns = column_name

In [120]:
data_amazon = pd.read_csv('amazon_cells_labelled.txt',sep = '\t', header = None)

In [121]:
data_amazon.columns = column_name

In [122]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [123]:
data_imdb = pd.read_csv('imdb_labelled.txt',sep ='\t', header = None)

In [124]:
data_imdb.columns = column_name

In [125]:
data_amazon.shape

(1000, 2)

In [126]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [127]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [128]:
# Append all the data in a single dataframe

In [129]:
data = data_yelp.append([data_amazon,data_imdb], ignore_index = True)

In [130]:
data.shape

(2748, 2)

In [131]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [132]:
data.tail()

Review  Sentiment
2743  I just got bored watching Jessice Lange take h...          0
2744  Unfortunately, any virtue in this film's produ...          0
2745                   In a word, it is embarrassing.            0
2746                               Exceptionally bad!            0
2747  All in all its an insult to one's intelligence...          0

In [133]:
#cheack distribution of sentiments

In [134]:
data['Sentiment'].value_counts

<bound method IndexOpsMixin.value_counts of 0       1
1       0
2       0
3       1
4       1
       ..
2743    0
2744    0
2745    0
2746    0
2747    0
Name: Sentiment, Length: 2748, dtype: int64>

In [135]:
# check for null values

In [136]:
data.isnull().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of       Review  Sentiment
0      False      False
1      False      False
2      False      False
3      False      False
4      False      False
...      ...        ...
2743   False      False
2744   False      False
2745   False      False
2746   False      False
2747   False      False

[2748 rows x 2 columns]>

In [137]:
x = data['Review']

In [138]:
y = data['Sentiment']

 2 Data **Cleaning**

In [139]:
# here we will remove stopword, puntuations
# as well as we will apply lemmtization

Creat a function to clean the data

In [140]:
import string 

In [141]:
punct = string.punctuation

In [142]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [143]:
from spacy.lang.en.stop_words import STOP_WORDS

In [144]:
stopwords = list(STOP_WORDS) # list of stopwords

In [145]:
#stopwords

In [146]:
# craeting a function for data cleaniing 

In [155]:
import spacy
nlp = spacy.load('en_core_web_sm')

def  text_data_cleaning(sentence):
  doc = nlp(sentence)
  tokens = [] # list of tokens
  for token in doc:
    if token.lemma_!= "-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      tem = token.lower_
    tokens.append(temp)

  cleaned_tokens = []
  for token in tokens:
      if token not in stopwords and token not in punct:
        cleaned_tokens.append(token)
  return cleaned_tokens
      

if root form of that word is not pronoun then it is going to convert that into lower form.
and if that word is a proper noun, then we are directly taking lower form, becoz there is no  lemmma

In [156]:
(text_data_cleaning("Hello all, It's a beutiful day outside there!"))
 

['hello', 'beutiful', 'day', 'outside']

Vectorization Feature Engineering (TFIDF)

In [159]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [161]:
tfidf = TfidfVectorizer(tokenizer = text_data_cleaning)
# tokenizer = text_data_cleaning, tokenization will be done according to this function

In [162]:
classifier = LinearSVC()

3) Train the model

Splitting the dataset into Train and Test

In [164]:
from sklearn.model_selection import train_test_split
x_train, x_text, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0 ) 

In [165]:
x_train.shape, x_text.shape

((2198,), (550,))

In [166]:
x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

Fit the x_train and y_train

In [168]:
clf = Pipeline([('tfidf', tfidf),('clf',classifier)])

In [170]:
clf.fit(x_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x7f52e8c96310>)),
                ('clf', LinearSVC())])

Predict the test set results

In [171]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [172]:
y_pred = clf.predict(x_text)

In [174]:
# confusion_matix 
confusion_matrix(y_test, y_pred)

array([[200,  79],
       [ 51, 220]])

In [176]:
# classification report 
print(classification_report(y_test, y_pred))
# we are getting almost 77% accurcy

              precision    recall  f1-score   support

           0       0.80      0.72      0.75       279
           1       0.74      0.81      0.77       271

    accuracy                           0.76       550
   macro avg       0.77      0.76      0.76       550
weighted avg       0.77      0.76      0.76       550



In [178]:
accuracy_score(y_test, y_pred)
# 76# accuracy

0.7636363636363637

In [180]:
clf.predict(['wow, i am learning  Natural Language Processing in the fashion!'])
# output is 1, that means review is positive

array([1])

In [183]:
clf.predict(["It's hard to learn new things"])
# output is 0, that means review is negative

array([0])